version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen_app
    volumes:
      - ./lumen-app:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: lumen_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lumen
      MYSQL_USER: lumenuser
      MYSQL_PASSWORD: lumenpassword
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
